; PlatformIO Project Configuration File
[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; PSRAM 核心配置（ESP32-S3 N16R8）
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi

; Flash 配置
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv

monitor_speed = 115200
upload_speed = 921600
board_build.f_cpu = 240000000


lib_deps =
    bodmer/TFT_eSPI @ ^2.5.0

build_flags =
    -include src/tft_fix.h
    -DBOARD_HAS_PSRAM
    -DCONFIG_SPIRAM_USE=1
    -DCONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY=1
    -DCONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=0
    -DCONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL=32768
    -DARDUINO_LOOP_STACK_SIZE=32768
    -D USER_SETUP_LOADED=1
    -D ST7789_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MISO=13
    -D TFT_MOSI=11
    -D TFT_SCLK=12
    -D TFT_CS=10
    -D TFT_DC=9
    -D TFT_RST=14
    -D TFT_BL=8
    -D TFT_BACKLIGHT_ON=1
    -D SPI_FREQUENCY=80000000
    -D SPI_READ_FREQUENCY=20000000
    -D SMOOTH_FONT=1
    -D TFT_INVERSION_ON
    -D TFT_RGB_ORDER
    -D CORE_DEBUG_LEVEL=0
